add persistence to JSON file for flashcards in hidden directory
reorproject/reor pull request #190
Opened 2024-04-09 01:03 UTC by chuyouchia

2024-04-09 15:46 UTC, chuyouchia commented on src/components/Chat/Chat.tsx
> +    const [actualOutput, _fileReferences] = messageToBeParsed.split(
this should be safe, even if the output doesn't contain file delimiter because it will by default return original output

2024-04-09 15:46 UTC, chuyouchia commented on src/components/Chat/Chat.tsx
> +                    4
This uses native pretty printing of JSON

2024-04-09 16:27 UTC, samlhuillier commented
This seems to contain a lot of work to parse the generated flashcard strings in the right format. Shouldn't we just use function calling and JSON mode (from Ollama) to generate the json directly? That should give us better performance and better adherence to the types

2024-04-11 15:10 UTC, samlhuillier requested changes

2024-04-11 15:10 UTC, samlhuillier commented on src/components/Chat/Chat.tsx
> +                  filePath: `${window.electronStore.getUserDirectory()}/.flashcards/${trimmedFileName}.json`,
Minor issue here with paths for windows - why now use ```window.path.join```?

2024-04-11 15:38 UTC, samlhuillier commented
I'm not too keen on the amount of custom logic for flashcards there is now in the chat component. Ideally in the follow on PRs, in addition to making the component to interact with generated flashcards, we should also have the logic for generating flashcards there and not in Chat.tsx.

2024-04-13 18:00 UTC, chuyouchia commented
> I'm not too keen on the amount of custom logic for flashcards there is now in the chat component. Ideally in the follow on PRs, in addition to making the component to interact with generated flashcards, we should also have the logic for generating flashcards there and not in Chat.tsx.

Yeah we should definitely separate them out, so that chat can be more pure and focused.

2024-04-13 18:01 UTC, chuyouchia commented
> This seems to contain a lot of work to parse the generated flashcard strings in the right format. Shouldn't we just use function calling and JSON mode (from Ollama) to generate the json directly? That should give us better performance and better adherence to the types

Documenting our discussion here - Streaming and JSON mode is not very compatible, because the information comes in bits and pieces, it is hard to parse it properly for a chat message compatible format. However, function calling is going to be huge in other tasks that we delegate to our chat agent to do

2024-04-13 19:50 UTC, samlhuillier approved these changes
lgtm

2024-04-13 20:24 UTC, merged