feat: trigger writing assistant without highlighting text completed
reorproject/reor pull request #359
Opened 2024-08-18 13:27 UTC by weilirs

fix #349 
/claim #349 

https://github.com/user-attachments/assets/82033104-f7ce-4a5e-9a5c-2e159c5dd2b9

2024-08-19 21:08 UTC, joseplayero requested changes
looks nice. made a small comment on the prompt.

some extra thoughts:
- some users may not like seeing the 'press space' text in every new line so maybe we think through ways to allow them to hide it (either in settings or like the message hides after being shown once per note)
- there is a small bug when resizing screen and the message changing places

2024-08-22 01:29 UTC, weilirs commented on src/components/Writing-Assistant/WritingAssistantFloatingMenu.tsx
> +      selectedText = ''
I modified how it handles customized prompts, please take a look

2024-08-23 23:27 UTC, joseplayero approved these changes
lg @weilirs 

one thought on this

the backlink extension code could be moved at some point to the EditorManager file because it does very similar things to what you're doing in this PR and moving it would clean up lots of our code (especially in how we pass around the suggestion state )

2024-08-23 23:27 UTC, joseplayero commented
/tip $20

2024-08-24 01:32 UTC, weilirs commented
> lg @weilirs
> 
> one thought on this
> 
> the backlink extension code could be moved at some point to the EditorManager file because it does very similar things to what you're doing in this PR and moving it would clean up lots of our code (especially in how we pass around the suggestion state )

Okay, I'll take a look

2024-08-24 01:32 UTC, merged