Added Send Button and Dropdown in Chatbot Homelayout
reorproject/reor pull request #382
Opened 2024-08-27 10:32 UTC by itsdheerajdp

/claim #381
Fixes : #381

After adding the changes , now the home layout looks like below 

![reor](https://github.com/user-attachments/assets/4bde71ea-51fc-43dc-b995-19439828652f)

2024-08-27 22:07 UTC, joseplayero requested changes
thanks for making @itsdheerajdp 

you do not need to interface the invoke function to the renderer process. you need to only call the function ``` await window.llm.getLLMConfigs()``` to get the llm configs and the equivalent get/set default llm function

also please keep the code clean and consistent, state variables go at the top of a component

2024-08-28 05:11 UTC, itsdheerajdp commented
@joseplayero I made the requested changes , kindly check it out ..

2024-08-29 20:40 UTC, joseplayero approved these changes

2024-08-29 20:40 UTC, merged

2024-08-30 16:52 UTC, itsdheerajdp commented
/claim #381