refactor: remove note creation modal
reorproject/reor pull request #431
Opened 2024-10-05 17:32 UTC by ezhil56x

/claim #427 

- New file will be created without a modal
- By default Untitled will be the name of the new file
- The name of the file depends on the first 20 characters of the first line of the file

https://github.com/user-attachments/assets/59a61c2e-d9a6-4ed5-b82b-75575f6526d5

2024-10-05 17:45 UTC, joseplayero commented on src/components/File/NewNote.tsx
> +  const createNewFile = async () => {
we can get of the newnote component fully right? this function can just go in the iconssidebar where the icon for new note is pressed and we can fully delete the newnotecomponent

2024-10-05 17:53 UTC, joseplayero commented on src/contexts/FileContext.tsx
> +        const newFileName = `${firstLine
can this sanitization and file naming code be moved to a separate function please

2024-10-05 18:04 UTC, joseplayero requested changes

2024-10-05 18:04 UTC, joseplayero commented on src/contexts/FileContext.tsx
> +          .replace(/[^a-zA-Z0-9-_ ]/g, '')
also this code will require similar checks to what is done above with getAllFilenamesInDirectory to ensure  files aren't overwritten if they have the same first 20 characters or so

2024-10-05 18:08 UTC, joseplayero commented on src/contexts/FileContext.tsx
> +        await window.fileSystem.renameFileRecursive({
also, renaming the file should only occur once. 
only the first time the file is saved after the user has modified the content. we can determine this if the filename has untitled in it

2024-10-06 08:04 UTC, ezhil56x commented
@joseplayero Should I remove the NewNote component fully. If so can I move the functions that are required to create a new note to FileContext?

2024-10-06 08:04 UTC, ezhil56x commented
Resolved other changes

2024-10-06 16:44 UTC, joseplayero commented
i still see some bugs and places for improvement @ezhil56x 

and i dont have time right now to review properly but will get back to you at the end of the week with a full review. does that sound fine to you?

2024-10-06 17:10 UTC, ezhil56x commented
Sounds good

2024-10-10 14:31 UTC, joseplayero commented
this become larger refactor so i will take over completing the task.

i have issued the bounty to thank for help @ezhil56x

2024-10-13 13:30 UTC, merged

2024-10-29 14:14 UTC, ezhil56x commented
@joseplayero
Can you add `hacktoberfest-accepted` label to this PR. It will help me complete [hacktoberfest](https://hacktoberfest.com/) this year.
Thanks!